apiVersion: apps/v1
kind: Deployment
metadata :
    name: ngx-dep
    labels:
        app: web
spec:
    replicas: 1
    selector:
        matchLabels:
           app: web
    template:
        metadata:
            name: ngx-pod
            labels:
             app: web
        spec:
            restartPolicy: Always
            containers:
             - name: nginx
               imagePullPolicy: Never
               image: my-nginx
               ports:
                - containerPort: 80
                - containerPort: 22
---
apiVersion: apps/v1
kind: Deployment
metadata :
    name: ftps-dep
    labels:
        app: ftp
spec:
    replicas: 1
    selector:
        matchLabels:
            app: ftp
    template:
        metadata:
            name: ftp-pod
            labels:
             app: ftp
        spec:
            volumes:
                - name: ftp-storage
                  persistentVolumeClaim:
                    claimName: ftp-pvc
            restartPolicy: Always
            containers:
             - name: ftps
               imagePullPolicy: Never
               image: my-ftp
               ports:
                - containerPort: 21
                - containerPort: 21000
                - containerPort: 21001
                - containerPort: 21002
                - containerPort: 21003
                - containerPort: 21004
                - containerPort: 21005
                - containerPort: 21006
                - containerPort: 21007
                - containerPort: 21008
                - containerPort: 21009
                - containerPort: 21010
               volumeMounts:
                - mountPath: "/home/mbani"
                  name: ftp-storage
---
    apiVersion: v1
    kind: Service
    metadata: 
        name: ngx-svc
    spec:
        ports:
            - name: https
              protocol: TCP
              port: 82
              targetPort: 80
        selector:
            app: web
---
    apiVersion: v1
    kind: Service
    metadata: 
        name: ngx-ssh
    spec:
        type: NodePort
        ports:
            - name: ssh
              protocol: TCP
              port: 21
              targetPort: 22
              nodePort: 222
        selector:
            app: web
---
apiVersion: v1
kind: Service
metadata: 
    name: ftps-svc
spec:
    type: NodePort
    ports:
          - name: ftp
            port: 21
            targetPort: 21
            nodePort: 21
          - name: ftps
            port: 21000
            targetPort: 21000
            nodePort: 21000
          - name: ftps1
            port: 21001
            targetPort: 21001
            nodePort: 21001
          - name: ftps2
            port: 21002
            targetPort: 21002
            nodePort: 21002
          - name: ftps3
            port: 21003
            targetPort: 21003
            nodePort: 21003
          - name: ftps4
            port: 21004
            targetPort: 21004
            nodePort: 21004
          - name: ftps5
            port: 21005
            targetPort: 21005
            nodePort: 21005
          - name: ftps6
            port: 21006
            targetPort: 21006
            nodePort: 21006
          - name: ftps7
            port: 21007
            targetPort: 21007
            nodePort: 21007
          - name: ftps8
            port: 21008
            targetPort: 21008
            nodePort: 21008
          - name: ftps9
            port: 21009
            targetPort: 21009
            nodePort: 21009
          - name: ftps10
            port: 21010
            targetPort: 21010
            nodePort: 21010
    selector:
        app: ftp