apiVersion: v1
kind: Service
metadata: 
    name: ftp-svc
spec:
    type: NodePort
    ports:
        - name: ftp
          port: 20
          targetPort: 21
          nodePort: 21
    selector:
        app: ftp