apiVersion: apps/v1
kind: Deployment
metadata :
    name: wordpress-dep
    labels:
        app: wdp
spec:
    replicas: 1
    selector:
        matchLabels:
           app: wdp
    template:
        metadata:
            name: wordpress-pod
            labels:
             app: wdp
        spec:
            restartPolicy: Always
            containers:
             - name: wordpress
               imagePullPolicy: Never
               image: my-wdp
               ports:
                - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata: 
    name: wordpress-svc
spec:
    type: NodePort
    ports:
        - name: wordpress
          port: 5050
          targetPort: 5050
          nodePort: 5050
    selector:
        app: wdp