apiVersion: 1
datasources:
- name: telegraf
  type: influxdb
  access: proxy
  database: telegraf
  user: admin
  url: http://influxdb-svc:8086
  jsonData:
    timeInterval: "10s"
  secureJsonData:
    password: mbani